### ISSUE TITLE
document how to disable minification on production

### ISSUE THREAD

**Issue by rosenfeld** [brian428/grails-coffeescript-compiler-plugin#1]
Could you please document how one could disable minification under production environment?

Some people will prefer let minification concerns to the resources plugin.

Currently I don't minify my assets on production and only deploy gzip compression to them. This allows me to debug some bugs that only show up on production... Also I didn't experienced much performance improvement on page loading when minifying my assets in addition to applying gzip compression on them.

**Comment by brian428** [comment]
Hi, right now it is automatic. I'll add a config option to enable or disable this in production.

**Comment by brian428** [comment]
Updated to include this option. Details in docs and README.md.

**Comment by rosenfeld** [comment]
Thank you very much!
