### ISSUE TITLE
grails clean should delete the compiled js files too

### ISSUE THREAD

**Issue by basejump** [brian428/grails-coffeescript-compiler-plugin#12]
this would keep it consistent.
we use the overrideJS = false so it only compiles new files just like a groovy file would do.

**Comment by brian428** [comment]
Sorry, I don't really understand what you're asking for. Please explain in more detail.

**Comment by basejump** [comment]
when I do a "grails clean" is removes all the compiled classes from target. then a grails compile will do just that.
It would be more consitent to look at the coffee files like groovy or java files. 
a clean would remove all the compiles js files and a "compile" would compile the coffee files
does that make sense? great plugin BTW, we are loving it.
I might have one of my team fork this and add the events in if we have some time this week

**Comment by stokito** [comment]
:+1:

**Comment by brian428** [comment]
If someone wants to take a stab at this and all the tests still pass, I'm all for it. But the documentation on getting a plugin to tie into the compile event is very sparse, and I don't see any built-in event at all for clean. So I really don't have time to try and mess with this myself right now. I host or contribute to a number of open-source projects on top of my full-time job, so time is always an enemy. :-)

**Comment by basejump** [comment]
https://gist.github.com/basejump/9924224
I created a gist here to show how how a clean can be done and a compile in _Events.groovy instead using doWithWebDescriptor in your plugin file. using events with something like this is a better way to go. Its follow the groovy files now so when do a "grails compile" I can expect that all my source will get compiled. Same with "grails clean" I can now expect all my compiled files to get zapped

**Comment by brian428** [comment]
Sorry for the delay. I'll try to take a look at this soon. I've actually switched most of my apps to use the Asset Pipeline plugin, since it supports CS compilation as well as generating aggregated files and manifests. So my use of the CS compiler plugin has been steadily dropping lately.

**Comment by basejump** [comment]
is your goal to have the coffee compilation be part of a plugin to this? looks intereseting http://grails.org/plugin/asset-pipeline

**Comment by brian428** [comment]
Not really....the asset pipeline already has a CS plugin, so it's pretty much already set. :-)

**Comment by brian428** [comment]
Just closing this since at this point, everyone should probably be using the asset pipeline.
