### ISSUE TITLE
Merge grails-coffeescript-compiler-plugin with grails-coffeescript-resources

### ISSUE THREAD

**Issue by stokito** [brian428/grails-coffeescript-compiler-plugin#13]
Hi Brian,

Thanks for your plugin. I'm choosing plugin to enable in my project and little bit confused because there is two similar plugins: your grails-coffeescript-compiler-plugin and grails-coffeescript-resources.The second one looks little it outdated and has a lot of unresolved issues in tracker.
But I want to be able use Coffee files as usual resources.
Could you answer to me what are the differences between this plugins and could they be merged?

Thanks

**Comment by brian428** [comment]
This plugin doesn't use the resources plugin. We had numerous problems with the resources plugin, with a big one being that it was causing problems with our load balancer. So I needed an option that left the choice of whether you want to use the resources plugin with the generated .js files up to the developer. You SHOULD be able to use the generated .js files just like any other .js resource as far as the resources plugin goes.

I also didn't like the fact that the grails-coffeescript-resources plugin requires you to individually specify the .coffee files it should process. I could find no way to tell it to process a directory tree, and we have dozens or hundreds of .coffee files, so listing them individually is not an option.

So to answer your question: no, these can't be merged.
