### ISSUE TITLE
Explicit selecting of compiler  

### ISSUE THREAD

**Issue by stokito** [brian428/grails-coffeescript-compiler-plugin#14]
In documentation said:

```
The default compiler uses a bundled version of Rhino, but if you have node coffee-script installed that will be used instead. Hopefully this does not cause any variances amongst environments with and without node coffee-script, but note that it COULD.
```

Maybe it would be good to create an option for explicit selecting of compiler?
For example I don't want to use nodejs installed on my system and I prefer to use Rhyno.

Also I can't find any log messages that shows which compiler was used.

**Comment by stokito** [comment]
Aha, I found two options: `forceRhino` and `forceNode` that can control compiler choise. It would be great to mention them in documentation.
BTF there is two issue with them.
1. If future we can use other JS compiler, for example [Nashorn](http://openjdk.java.net/projects/nashorn/) that is a part of JDK8. So, boolean options might be not so agile as they should.
2. It looks like `forceNode` option is ignored
Please, take a look inside `CoffeescriptCompilerGrailsPlugin.doWithWebDescriptor()` closure. It contains option verriding for `forceRhino` but nothing for `forceNode`

``` groovy
    def doWithWebDescriptor = { xml ->
              ....
            coffeeCompilerManager.forceRhino = ( thisPluginConfig.containsKey( "forceRhino" ) ) ? thisPluginConfig.forceRhino as Boolean : false
              .....
    }
```

**Comment by brian428** [comment]
Thanks, merged your update to allow forcing node. I'll update the docs to mention these two options.

**Comment by stokito** [comment]
Thanks!

**Comment by brian428** [comment]
I should add that once I thought about this, the forceNode option really doesn't make any sense. The plugin defaults to using the Node compiler. The only reason it will use Rhino is if Node CoffeeScript isn't available, or if forceRhino is set to true. I'll leave it in, in case someone has some bizarre situation where forceNode would make sense, but I honestly can't think of a time it would be needed.
