### ISSUE TITLE
Does not compile coffee files from plugins ?

### ISSUE THREAD

**Issue by snimavat** [brian428/grails-coffeescript-compiler-plugin#17]
Lets say i have configred coffee compiler plugin in my app - app has two plugins installed both of the plugins has coffee files. Is there a way to have the coffee files inside the plugins to compiler automatically when compiling/running the main app? so that the plugins doesnt have to include the generated js files but just the coffess files. (with support for inline plugins)

**Comment by brian428** [comment]
No way that I know of. Actually, at this point I'd just recommend that you use the asset-pipeline plugin, since it has better support for compiling CS as well as many other types of resources.
